(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> 'Auth' object has no attribute 'first_name'"
p3
sS'layer'
p4
S'/home/hai/Projects/web2py/applications/FinalProject/controllers/game_menu.py'
p5
sS'code'
p6
S"# This controller will be used to display the list of open game to join\n\ndef index():\n\tfirst_name = auth.first_name\n\treturn dict(message=T('testing' + first_name))\nresponse._vars=response._caller(index)\n"
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/hai/Projects/web2py/gluon/restricted.py", line 224, in restricted\n    exec ccode in environment\n  File "/home/hai/Projects/web2py/applications/FinalProject/controllers/game_menu.py", line 6, in <module>\n  File "/home/hai/Projects/web2py/gluon/globals.py", line 392, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/hai/Projects/web2py/applications/FinalProject/controllers/game_menu.py", line 4, in index\n    first_name = auth.first_name\nAttributeError: \'Auth\' object has no attribute \'first_name\'\n'
p11
s.